USE WORLD;
SHOW TABLES;
DESCRIBE COUNTRY;
DESCRIBE CITY;
DESCRIBE COUNTRYLANGUAGE;
ALTER TABLE CITY ADD COLUMN is_population_large BOOLEAN;
UPDATE CITY SET is_population_large = CASE WHEN POPULATION > 1000000 THEN TRUE ELSE FALSE END;
ALTER TABLE COUNTRY ADD COLUMN region_code CHAR(3) DEFAULT 'NA';
ALTER TABLE CITY ADD CONSTRAINT chk_population CHECK (population >=0);
ALTER TABLE COUNTRY ADD CONSTRAINT unq_code UNIQUE (code);
CREATE INDEX idx_city_name ON city(name);

